16:32:11  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
16:32:11  [INFO ] : 测试失败！
16:32:11  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"92c81a9e765748bf8609be1a71b36822"}
16:32:11  [INFO ] : 测试通过！
16:32:11  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"用户已退出登录"}
16:32:11  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
16:32:11  [INFO ] : 测试失败！
16:32:11  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
16:32:11  [ERROR] : 保存参数失败
16:32:11  [ERROR] : java.lang.NullPointerException
java.lang.NullPointerException: null
	at inter.KeywordOfInter.saveParam(KeywordOfInter.java:117) ~[classes/:?]
	at Mail.a.b(a.java:26) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.1.0.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.1.0.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.1.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_181]
	at org.testng.TestRunner.privateRun(TestRunner.java:766) [testng-7.1.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:587) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:286) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.1.0.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109) [testng-7.1.0.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1039) [testng-7.1.0.jar:?]
	at org.testng.TestNG.run(TestNG.java:1007) [testng-7.1.0.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
16:32:11  [INFO ] : 测试失败！
16:32:11  [INFO ] : 在keyword中调试输出返回的结果是{"status":405,"msg":"非法请求"}
16:32:34  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"success","token":"a3bdc124f32647eea0cb7753c5946afc"}
16:32:35  [INFO ] : 测试通过！
16:32:35  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"恭喜您，登录成功","userid":"1065"}
16:32:35  [INFO ] : 测试通过！
16:32:35  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"查询成功","nickname":"这是个老师","id":"1065","describe":"测试账号"}
16:32:35  [INFO ] : 测试通过！
16:32:35  [INFO ] : 在keyword中调试输出返回的结果是{"status":200,"msg":"用户已退出登录"}
